// examples/client-side-rendered/react/src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { defineCustomElements } from '@sbb-esta/lyne-components/dist/esm/loader';

defineCustomElements();

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// examples/client-side-rendered/angular/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { defineCustomElements } from '@sbb-esta/lyne-components/dist/esm/loader';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));

defineCustomElements();
